In [1]:
import numpy as np

In [3]:
arr = np.arange(0,11)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr[8]

8

In [6]:
arr[1:5]

array([1, 2, 3, 4])

In [7]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [8]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [9]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [10]:
arr[0:5] = 100

In [11]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [12]:
# NumPy can broadcast values to multiple slots in a list

In [13]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [14]:
arr = np.arange(0,11)

In [15]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
slice_of_array = arr[0:6]

In [18]:
slice_of_array[:] = 99

In [19]:
slice_of_array

array([99, 99, 99, 99, 99, 99])

In [20]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [21]:
# Note that NumPy just gives a reference not a copy

In [22]:
arr_copy = arr.copy()

In [23]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [24]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [25]:
arr_copy[:] = 100

In [26]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [27]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [29]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [39]:
arr_2d[2][1]

40

In [40]:
arr_2d[1,2]

30

In [41]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [48]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [49]:
arr_2d[:2,:2]

array([[ 5, 10],
       [20, 25]])

In [51]:
arr = np.arange(1,11)

In [53]:
bool_arr = arr > 5

In [54]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [55]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [56]:
arr[arr > 5]

array([ 6,  7,  8,  9, 10])

In [57]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [58]:
arr[arr < 3]

array([1, 2])

In [60]:
arr_2d = np.arange(50).reshape(5,10)

In [61]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [62]:
arr_2d[2:,2:]

array([[22, 23, 24, 25, 26, 27, 28, 29],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [42, 43, 44, 45, 46, 47, 48, 49]])