In [1]:
import numpy as np

In [2]:
my_list = [1,2,3]

In [4]:
arr = np.array(my_list)

In [5]:
arr

array([1, 2, 3])

In [6]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [7]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [13]:
np.zeros(3)

array([0., 0., 0.])

In [15]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [18]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [25]:
np.linspace(1,10,100)

array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
        1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
        1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
        2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
        2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
        3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
        3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
        4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
        4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
        5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
        5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
        6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
        6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
        6.90909091,  7.        ,  7.09090909,  7.18181818,  7.27

In [26]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [27]:
# Identity Matrix - 2D square matrix with a diagonal of 1's

In [28]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [30]:
np.random.rand(5,5)

array([[0.52529348, 0.10653648, 0.79119368, 0.67828173, 0.46359442],
       [0.87969475, 0.7349102 , 0.41632701, 0.96244582, 0.29399098],
       [0.79787436, 0.90406038, 0.33677736, 0.83740068, 0.89387653],
       [0.34724866, 0.47850993, 0.76444004, 0.62485481, 0.80358932],
       [0.01500481, 0.37105255, 0.68407789, 0.01043389, 0.86363467]])

In [31]:
np.random.randn(2)

array([ 0.55194687, -0.21886974])

In [32]:
# Randn gives random numbers from a normal distribution curve, no need to pass in a tuple

In [34]:
np.random.randint(1,100,5)

array([88, 66,  1, 51,  3])

In [35]:
arr = np.arange(25)

In [36]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [37]:
ranarr = np.random.randint(0,50,10)

In [38]:
ranarr

array([45, 13, 12,  7, 49, 43, 47, 15,  8, 18])

In [39]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [41]:
ranarr.max()

49

In [43]:
ranarr.min()

7

In [44]:
ranarr.argmax()

4

In [45]:
ranarr.argmin()

3

In [46]:
arr.shape

(25,)

In [47]:
ranarr.shape

(10,)

In [48]:
arr = arr.reshape(5,5)

In [49]:
arr.shape

(5, 5)

In [50]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [51]:
arr.dtype

dtype('int64')

In [52]:
ranarr.dtype

dtype('int64')

In [53]:
from numpy.random import randint

In [55]:
randint(2,10)

5

In [56]:
# you can import specific methods