In [85]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import StandardScaler

In [86]:
data = pd.read_csv('fbdh1.csv')
data.drop(['Flow'], axis = 1, inplace = True)

In [87]:
data

D1      D2      P1     P2    dD1    dD2    dP1   dP2
0      99.49 -145.71   48.04 -15.90  81.17  12.26  36.71  2.21
1     172.78 -118.66   79.84 -11.94  80.09  18.49  35.48  2.91
2     242.66  -81.28  109.77  -7.75  75.74  24.65  33.03  3.26
3     316.42  -55.50  140.84  -5.30  74.07  28.43  31.89  3.37
4     392.40  -31.67  171.92  -1.24  73.96  29.70  31.32  3.68
...      ...     ...     ...    ...    ...    ...    ...   ...
6659 -536.68 -332.43 -215.22 -47.35   4.00  14.70   2.12  2.09
6660 -534.44 -334.46 -213.79 -47.58   3.27  10.50   1.79  1.50
6661 -533.05 -334.28 -213.32 -47.54   2.21   5.08   1.24  0.68
6662 -535.65 -344.73 -214.28 -48.81   0.70  -0.31   0.48 -0.02
6663 -542.67 -334.89 -217.24 -47.56  -2.00  -2.48  -0.76 -0.30

[6664 rows x 8 columns]

In [88]:
scaler = StandardScaler()
scaler.fit(data)
data = scaler.transform(data)

In [89]:
data = np.float32(data)

In [90]:
data

array([[ 0.20946573, -0.13723774,  0.24811451, ...,  0.13870831,
         1.6885595 ,  0.3524548 ],
       [ 0.3694566 , -0.11278185,  0.41600335, ...,  0.20938598,
         1.6319983 ,  0.4644174 ],
       [ 0.5220035 , -0.07898661,  0.57401943, ...,  0.27926952,
         1.5193356 ,  0.5203987 ],
       ...,
       [-1.1713587 , -0.3077238 , -1.1317416 , ...,  0.05725314,
         0.05748079,  0.10773662],
       [-1.1770345 , -0.31717163, -1.13681   , ..., -0.00389495,
         0.02253238, -0.00422596],
       [-1.192359  , -0.30827528, -1.1524373 , ..., -0.02851301,
        -0.03448869, -0.04901099]], dtype=float32)

In [84]:
np.savetxt('test1.txt', data)

In [77]:
b = np.loadtxt('test1.txt')

In [78]:
b = np.float32(b)

In [79]:
b

array([[ 0.20946573, -0.13723774,  0.24811451, ...,  0.13870831,
         1.6885595 ,  0.3524548 ],
       [ 0.3694566 , -0.11278185,  0.41600335, ...,  0.20938598,
         1.6319983 ,  0.4644174 ],
       [ 0.5220035 , -0.07898661,  0.57401943, ...,  0.27926952,
         1.5193356 ,  0.5203987 ],
       ...,
       [-1.1713587 , -0.3077238 , -1.1317416 , ...,  0.05725314,
         0.05748079,  0.10773662],
       [-1.1770345 , -0.31717163, -1.13681   , ..., -0.00389495,
         0.02253238, -0.00422596],
       [-1.192359  , -0.30827528, -1.1524373 , ..., -0.02851301,
        -0.03448869, -0.04901099]], dtype=float32)

In [53]:
for i in range(0, len(b)):
        
        input_data = b[i]
        print(input_data)

[0.4642777  0.21555082 0.5279661  0.26247633 0.7533531  0.5501804
 0.7524719  0.5297287 ]
[0.49159783 0.21872325 0.55663544 0.27053937 0.7510968  0.55703163
 0.7456394  0.543198  ]
[0.5176468  0.22310716 0.5836188  0.2790707  0.7420089  0.56380594
 0.7320298  0.54993266]
[0.5451421  0.22613063 0.61163    0.2840592  0.73852    0.5679629
 0.72569716 0.5520493 ]
[0.57346493 0.2289254  0.6396502  0.29232585 0.73829025 0.56935954
 0.72253084 0.5580142 ]
[0.602496   0.23039493 0.6677155  0.29605195 0.74152845 0.56482863
 0.72241974 0.54974025]
[0.62643886 0.22974403 0.6904165  0.29478955 0.740066   0.5539964
 0.7171425  0.5303059 ]
[0.6559136  0.22936521 0.7178237  0.29399547 0.7398571  0.5443738
 0.713143   0.5102944 ]
[0.68327093 0.23027764 0.7431302  0.29464704 0.739105   0.53904015
 0.70942116 0.49143738]
[0.71052396 0.2340306  0.76764333 0.2997577  0.7391259  0.5447257
 0.7067548  0.4956706 ]
[0.73447055 0.23870537 0.7891363  0.30769858 0.7380604  0.5585492
 0.7035885  0.5185684 ]
[0.74

 0.69792247 0.54800844]
[0.46887395 0.22347425 0.53690946 0.28723556 0.70062256 0.55879116
 0.6882013  0.54743123]
[0.4908113  0.22613767 0.55978185 0.29470813 0.6988259  0.559693
 0.6840907  0.54723877]
[0.5130841  0.22944261 0.5829066  0.30232322 0.7008106  0.56170547
 0.6844795  0.5522417 ]
[0.5372879  0.23065177 0.6073837  0.30635473 0.7060962  0.55928606
 0.68847907 0.5482009 ]
[0.55886364 0.23060955 0.62882257 0.30659908 0.70868677 0.5524568
 0.688979   0.5308832 ]
[0.57943666 0.23082183 0.6489452  0.30712846 0.70724523 0.54467076
 0.68509054 0.51087165]
[0.6005316  0.23238164 0.6696087  0.31052878 0.70446664 0.5404698
 0.67998    0.49951896]
[0.62561136 0.23596337 0.6934998  0.3169222  0.70588726 0.5464963
 0.6795356  0.5072157 ]
[0.6534496  0.24068388 0.7198071  0.3280394  0.7163331  0.5587032
 0.6888124  0.5335771 ]
[0.67929727 0.2454173  0.74356294 0.3383829  0.7270714  0.57031626
 0.69792247 0.559746  ]
[0.7029195  0.25058582 0.76482147 0.3494187  0.73143774 0.57835525
 0.69

 0.5189979  0.45603234]
[0.22868145 0.21269742 0.27555895 0.24449739 0.5603769  0.52585447
 0.5174425  0.45949587]
[0.22705619 0.21067668 0.27359357 0.24001792 0.56273764 0.52400696
 0.52083105 0.45814893]
[0.22228104 0.20849176 0.26786873 0.23517194 0.56351066 0.52046585
 0.52188647 0.45102945]
[0.2183148  0.20813875 0.26309952 0.23568098 0.5627585  0.5210597
 0.52088654 0.45487782]
[0.21620867 0.20805664 0.26055714 0.23580314 0.5632808  0.52428186
 0.5214976  0.4639215 ]
[0.21852355 0.20810239 0.26333395 0.23728952 0.5693394  0.53027534
 0.5294967  0.4802771 ]
[0.22308621 0.20848003 0.26879734 0.23847046 0.58348304 0.53562003
 0.5481613  0.49297673]
[0.23022844 0.20938191 0.277326   0.24187079 0.5998203  0.5385673
 0.56965894 0.49971136]
[0.24115796 0.20959653 0.29056075 0.24398835 0.6172857  0.5400849
 0.5928786  0.5056763 ]
[0.25665018 0.20924234 0.3088442  0.24362186 0.63583755 0.5393151
 0.61704254 0.5033673 ]
[0.27584767 0.20947456 0.3311666  0.24683893 0.6572306  0.53796244
 0.

[0.53189766 0.15951808 0.61055714 0.24382547 0.55291855 0.43640304
 0.51022106 0.32172406]
[0.52046865 0.15254344 0.597665   0.23185307 0.5462541  0.44477192
 0.5021109  0.3342313 ]
[0.511101   0.14514779 0.5869005  0.22014537 0.53825265 0.45748472
 0.49200088 0.35520494]
[0.50750005 0.13698511 0.5824378  0.20581108 0.5373125  0.46756917
 0.49038994 0.37175295]
[0.5065085  0.1282724  0.5808421  0.19145644 0.54953414 0.46536973
 0.50455505 0.36655763]
[0.50590837 0.1211371  0.57995856 0.18147944 0.566331   0.46335724
 0.5249417  0.3671349 ]
[0.5050659  0.11412729 0.57890373 0.16926272 0.5776334  0.4645779
 0.5392179  0.36944392]
[0.5040781  0.10844743 0.57773167 0.15883778 0.580788   0.47034046
 0.54377294 0.37810275]
[0.5026392  0.10481058 0.5757843  0.15203714 0.58024484 0.48069987
 0.5433285  0.39118722]
[0.49381578 0.10424529 0.56612873 0.15230183 0.5708436  0.4956451
 0.5321631  0.41485474]
[0.4791474  0.10506742 0.549405   0.15407325 0.5510383  0.51458234
 0.5077769  0.4506446 ]
[

 0.58160204 0.33442372]
[0.40795633 0.18775201 0.47830868 0.26551014 0.6006769  0.41047156
 0.56443727 0.34616125]
[0.40614468 0.17936768 0.4768031  0.25728422 0.5910667  0.4336647
 0.5551605  0.36636522]
[0.40231264 0.17102674 0.47247565 0.24814203 0.5796808  0.448379
 0.5437174  0.38233596]
[0.39597562 0.16492818 0.46558782 0.24138212 0.56430453 0.4615757
 0.5257749  0.40138543]
[0.38686144 0.16114005 0.45536423 0.23570134 0.54886556 0.476257
 0.5073325  0.4187031 ]
[0.3759841  0.15706223 0.44364408 0.22869709 0.53513974 0.48837593
 0.49050105 0.4238984 ]
[0.36808145 0.15040661 0.43518752 0.21666361 0.5274308  0.4932257
 0.48183537 0.41793343]
[0.3617183  0.14674161 0.42783087 0.2101073  0.5275561  0.49489728
 0.4817798  0.41196844]
[0.35629827 0.14132798 0.42161018 0.20023212 0.5337609  0.492038
 0.48894566 0.4040793 ]
[0.34629694 0.14041907 0.40967363 0.19880684 0.53570384 0.49899924
 0.48961225 0.41620165]
[0.33866638 0.13799724 0.4004057  0.19589518 0.5335729  0.5094356
 0.485390

 0.51149875 0.4340966 ]
[0.31219247 0.22866154 0.37298054 0.30934784 0.55195755 0.51093125
 0.5093323  0.43351933]
[0.30773044 0.22480537 0.36804906 0.30163094 0.55291855 0.5047838
 0.5107766  0.42235905]
[0.2987654  0.22361264 0.35799676 0.2990654  0.55135167 0.50420094
 0.50916564 0.42255148]
[0.29042658 0.22279169 0.34884602 0.29721254 0.5461497  0.51175606
 0.50288856 0.43948433]
[0.2849208  0.2211439  0.34239992 0.2936697  0.5427652  0.5191242
 0.4981113  0.45218396]
[0.2838025  0.21950315 0.34108368 0.29147068 0.5485522  0.5229402
 0.50488836 0.4618049 ]
[0.28074583 0.21864702 0.33756763 0.2885183  0.5593532  0.5228632
 0.517998   0.4608428 ]
[0.27200073 0.221898   0.32724485 0.2826543  0.56046045 0.5312981
 0.5185535  0.45391572]
[0.26391912 0.22245392 0.31781465 0.2738379  0.55344087 0.5401069
 0.50949895 0.4404464 ]
[0.2594683  0.21839017 0.31259465 0.26031804 0.54694355 0.53698367
 0.501111   0.4135078 ]
[0.26413906 0.21591792 0.31770647 0.25653085 0.55803704 0.5271742
 0.514

 0.5398289  0.598807  ]
[0.8639661  0.13236195 0.8888839  0.20467086 0.51491666 0.619155
 0.49038994 0.6472965 ]
[0.7533139  0.16798802 0.8009376  0.26210982 0.36790207 0.694365
 0.3633485  0.7625553 ]
[0.62768763 0.19553587 0.6937613  0.29994094 0.17916684 0.7594356
 0.18936785 0.8456802 ]
[0.5480012  0.20308048 0.6206726  0.30765784 0.05887268 0.76657283
 0.06671481 0.83702135]
[0.5038507  0.20023057 0.57890373 0.30409464 0.07115698 0.69989663
 0.06221531 0.7231095 ]
[0.47740287 0.1945038  0.5528489  0.29709038 0.20991936 0.5940153
 0.17753583 0.56243986]
[0.45677018 0.19054678 0.5323386  0.2908395  0.35668325 0.52243435
 0.31252083 0.465076  ]
[0.43948498 0.18566677 0.5149657  0.28234887 0.43928885 0.4979765
 0.39373404 0.43178758]
[0.42240107 0.18095917 0.4976109  0.27538535 0.47434506 0.4951832
 0.42867458 0.423706  ]
[0.40771404 0.1740854  0.48223945 0.2647364  0.48909456 0.49224696
 0.4432841  0.41600925]
[0.39873037 0.16595322 0.47286332 0.25038177 0.50315464 0.4825034
 0.45772

In [99]:
data = np.loadtxt('test1.txt')

In [100]:
data

array([[ 0.20946573, -0.13723774,  0.24811451, ...,  0.13870831,
         1.68855953,  0.35245481],
       [ 0.36945659, -0.11278185,  0.41600335, ...,  0.20938598,
         1.6319983 ,  0.4644174 ],
       [ 0.52200347, -0.07898661,  0.57401943, ...,  0.27926952,
         1.51933563,  0.52039868],
       ...,
       [-1.1713587 , -0.30772379, -1.13174164, ...,  0.05725314,
         0.05748079,  0.10773662],
       [-1.1770345 , -0.31717163, -1.13680995, ..., -0.00389495,
         0.02253238, -0.00422596],
       [-1.19235897, -0.30827528, -1.15243733, ..., -0.02851301,
        -0.03448869, -0.04901099]])

In [56]:
data = np.float32([data])

In [63]:
len(data[0])

6664

In [61]:
data[0][2]

array([0.5176468 , 0.22310716, 0.5836188 , 0.2790707 , 0.7420089 ,
       0.56380594, 0.7320298 , 0.54993266], dtype=float32)

In [64]:
0.0008545255675321582 * 1000

0.8545255675321581

In [67]:
data[0][2].argmax()

4

In [68]:
data

array([[[0.4642777 , 0.21555082, 0.5279661 , ..., 0.5501804 ,
         0.7524719 , 0.5297287 ],
        [0.49159783, 0.21872325, 0.55663544, ..., 0.55703163,
         0.7456394 , 0.543198  ],
        [0.5176468 , 0.22310716, 0.5836188 , ..., 0.56380594,
         0.7320298 , 0.54993266],
        ...,
        [0.22848761, 0.19343539, 0.29233682, ..., 0.54228437,
         0.5554383 , 0.5002886 ],
        [0.22751841, 0.19220981, 0.29147133, ..., 0.53635687,
         0.55121654, 0.48681933],
        [0.22490159, 0.19336385, 0.28880274, ..., 0.5339704 ,
         0.5443284 , 0.4814316 ]]], dtype=float32)

In [91]:
data = np.loadtxt('test1.txt')

In [92]:
data = np.float32([data])

In [95]:
len(data[0])

6664

In [98]:
data[0][0].argmax()

6