In [38]:
import pandas as pd

In [39]:
df = pd.read_csv('iris.csv')

In [40]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0     0.0  
1     0.0  
2     0.0  
3     0.0  
4     0.0

In [41]:
df.columns

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)', 'target'],
      dtype='object')

In [42]:
df.columns = ['sepal_length', 'sepal_width', 'petal_length', 
             'pedal_width', 'target']

In [43]:
df.head()

sepal_length  sepal_width  petal_length  pedal_width  target
0           5.1          3.5           1.4          0.2     0.0
1           4.9          3.0           1.4          0.2     0.0
2           4.7          3.2           1.3          0.2     0.0
3           4.6          3.1           1.5          0.2     0.0
4           5.0          3.6           1.4          0.2     0.0

In [44]:
df['target'] = df['target'].apply(int)

In [45]:
df.head()

sepal_length  sepal_width  petal_length  pedal_width  target
0           5.1          3.5           1.4          0.2       0
1           4.9          3.0           1.4          0.2       0
2           4.7          3.2           1.3          0.2       0
3           4.6          3.1           1.5          0.2       0
4           5.0          3.6           1.4          0.2       0

In [46]:
y = df['target']

In [47]:
X = df.drop('target', axis = 1)

In [48]:
y

0      0
1      0
2      0
3      0
4      0
5      0
6      0
7      0
8      0
9      0
10     0
11     0
12     0
13     0
14     0
15     0
16     0
17     0
18     0
19     0
20     0
21     0
22     0
23     0
24     0
25     0
26     0
27     0
28     0
29     0
      ..
120    2
121    2
122    2
123    2
124    2
125    2
126    2
127    2
128    2
129    2
130    2
131    2
132    2
133    2
134    2
135    2
136    2
137    2
138    2
139    2
140    2
141    2
142    2
143    2
144    2
145    2
146    2
147    2
148    2
149    2
Name: target, Length: 150, dtype: int64

In [49]:
X

sepal_length  sepal_width  petal_length  pedal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
5             5.4          3.9           1.7          0.4
6             4.6          3.4           1.4          0.3
7             5.0          3.4           1.5          0.2
8             4.4          2.9           1.4          0.2
9             4.9          3.1           1.5          0.1
10            5.4          3.7           1.5          0.2
11            4.8          3.4           1.6          0.2
12            4.8          3.0           1.4          0.1
13            4.3          3.0           1.1          0.1
14            5.8          4.0           1.2          0.2
15            5.7          4.4           1.5          0.4
16            5.4          3.9           1.3          0.4
17            5.1          3.5           1.4          0.3
18            5.7          3.8           1.7          0.3
19            5.1          3.8           1.5          0.3
20            5.4          3.4           1.7          0.2
21            5.1          3.7           1.5          0.4
22            4.6          3.6           1.0          0.2
23            5.1          3.3           1.7          0.5
24            4.8          3.4           1.9          0.2
25            5.0          3.0           1.6          0.2
26            5.0          3.4           1.6          0.4
27            5.2          3.5           1.5          0.2
28            5.2          3.4           1.4          0.2
29            4.7          3.2           1.6          0.2
..            ...          ...           ...          ...
120           6.9          3.2           5.7          2.3
121           5.6          2.8           4.9          2.0
122           7.7          2.8           6.7          2.0
123           6.3          2.7           4.9          1.8
124           6.7          3.3           5.7          2.1
125           7.2          3.2           6.0          1.8
126           6.2          2.8           4.8          1.8
127           6.1          3.0           4.9          1.8
128           6.4          2.8           5.6          2.1
129           7.2          3.0           5.8          1.6
130           7.4          2.8           6.1          1.9
131           7.9          3.8           6.4          2.0
132           6.4          2.8           5.6          2.2
133           6.3          2.8           5.1          1.5
134           6.1          2.6           5.6          1.4
135           7.7          3.0           6.1          2.3
136           6.3          3.4           5.6          2.4
137           6.4          3.1           5.5          1.8
138           6.0          3.0           4.8          1.8
139           6.9          3.1           5.4          2.1
140           6.7          3.1           5.6          2.4
141           6.9          3.1           5.1          2.3
142           5.8          2.7           5.1          1.9
143           6.8          3.2           5.9          2.3
144           6.7          3.3           5.7          2.5
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [50]:
from sklearn.model_selection import train_test_split

In [51]:
X_train, X_test, y_train, y_test = train_test_split(
...     X, y, test_size=0.3)

In [52]:
import tensorflow as tf

In [53]:
# FEATURE COLUMNS

In [54]:
feat_cols = []

for col in X.columns:
    
    feat_cols.append(tf.feature_column.numeric_column(col))

In [55]:
feat_cols

[NumericColumn(key='sepal_length', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 NumericColumn(key='sepal_width', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 NumericColumn(key='petal_length', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 NumericColumn(key='pedal_width', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None)]

In [56]:
input_func = tf.estimator.inputs.pandas_input_fn(x = X_train, y = y_train, 
                                   batch_size = 10, 
                                   num_epochs = 5, 
                                   shuffle = True)

In [57]:
classifier = tf.estimator.DNNClassifier(hidden_units = [10, 20, 10, 10, 10, 10], 
                                       n_classes = 3, 
                                       feature_columns = feat_cols)

W0826 15:49:37.521447 4617192896 estimator.py:1811] Using temporary folder as model directory: /var/folders/j0/8hdcgtwn33v9lp5kvxshrvkm0000gn/T/tmpy4elh1xp


In [58]:
classifier.train(input_fn = input_func, steps = 50)

In [59]:
pred_fn = tf.estimator.inputs.pandas_input_fn(x = X_test, 
                                             batch_size = len(X_test), 
                                             shuffle = False)

In [60]:
predictions = list(classifier.predict(input_fn = pred_fn))

In [61]:
predictions

[{'logits': array([ 2.4658737, -4.2462015, -3.573878 ], dtype=float32),
  'probabilities': array([0.99641454, 0.00121178, 0.00237361], dtype=float32),
  'class_ids': array([0]),
  'classes': array([b'0'], dtype=object),
  'all_class_ids': array([0, 1, 2], dtype=int32),
  'all_classes': array([b'0', b'1', b'2'], dtype=object)},
 {'logits': array([ 2.5798376, -4.435266 , -3.6964452], dtype=float32),
  'probabilities': array([9.9722904e-01, 8.9572411e-04, 1.8751670e-03], dtype=float32),
  'class_ids': array([0]),
  'classes': array([b'0'], dtype=object),
  'all_class_ids': array([0, 1, 2], dtype=int32),
  'all_classes': array([b'0', b'1', b'2'], dtype=object)},
 {'logits': array([-2.635232  ,  0.61092466,  0.93494916], dtype=float32),
  'probabilities': array([0.01607344, 0.4129493 , 0.5709772 ], dtype=float32),
  'class_ids': array([2]),
  'classes': array([b'2'], dtype=object),
  'all_class_ids': array([0, 1, 2], dtype=int32),
  'all_classes': array([b'0', b'1', b'2'], dtype=object)},
 

In [62]:
final_preds = []

for pred in predictions:
    
    final_preds.append(pred['class_ids'][0])

In [63]:
final_preds

[0,
 0,
 2,
 1,
 0,
 0,
 2,
 2,
 2,
 0,
 0,
 2,
 1,
 0,
 2,
 2,
 1,
 2,
 1,
 0,
 2,
 2,
 0,
 2,
 0,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 2,
 2,
 1,
 2,
 2,
 2,
 1,
 0,
 0,
 1,
 0]

In [64]:
from sklearn.metrics import classification_report, confusion_matrix

In [65]:
print(confusion_matrix(y_test, final_preds))

[[15  0  0]
 [ 0 13  2]
 [ 0  0 15]]


In [66]:
print(classification_report(y_test, final_preds))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        15
           1       1.00      0.87      0.93        15
           2       0.88      1.00      0.94        15

   micro avg       0.96      0.96      0.96        45
   macro avg       0.96      0.96      0.96        45
weighted avg       0.96      0.96      0.96        45

